#!/bin/sh
ifname=$(uci get network.wan.ifname)
#ifname=${ifname%%.*}

res=$(cat /sys/class/net/$ifname/carrier)

[ $res -eq 0 ] && return 1;

return 0

#swconfig dev eth0 port 1 get link | grep "link:up"
