#! /bin/sh

usage()
{
	echo "getfirm <info>"
	echo "        MAC"
	echo "        SSID"
	echo "        PIN"	
	echo "        MODEL"
	echo "        FIRM"
	echo "        WEBSITE"
	echo "        HARDVERSION"
	echo "        SOFTVERSION"
	echo "        LANGUAGE"
	echo "        PRODUCT_ID"
	echo "        SPECIAL_ID"
	echo "        DEV_ID"
	echo "        HW_ID"
	echo "        FW_ID"
	echo "        OEM_ID"
	echo "        COUNTRY"	
}

option="$1"
factoryLanMac="00-0A-EB-AC-25-00"
factoryPIN="12345670"
tmpMAC=
cnt=0
mac_len=

case $option in
	MAC)
	# echo "====getfirm MAC=====" >/dev/console
	# rm -f /tmp/default-mac >/dev/null 2>&1
	nvrammanager -r /tmp/default-mac -p default-mac >/dev/null 2>&1

	tmpMAC=$(grep 'MAC'  /tmp/default-mac | cut -d : -f 2-)
	mac_len=${#tmpMAC}
			
	if [ $mac_len -lt 17 -o $mac_len -gt 18 ];then
		while [ $mac_len -lt 17 -o $mac_len -gt 18 ]; do
			  echo "get MAC failed!len:$mac_len" >/dev/console	  
				nvrammanager -r /tmp/default-mac -p default-mac >/dev/null 2>&1
				tmpMAC=$(grep 'MAC'  /tmp/default-mac | cut -d : -f 2-)
				mac_len=${#tmpMAC}
				
				cnt=`expr $cnt + 1`				
				if [ $cnt -gt 5 ];then
					#this is for MAC missing/error case....
					tmpMAC=$factoryLanMac
					break;
				fi
	  done	  
	fi
	echo $tmpMAC
	;;
	
	SSID)
	echo  "TP-Link"
	;;
	
	PIN)
	rm -f /tmp/pin >/dev/null 2>&1
	nvrammanager -r /tmp/pin -p pin >/dev/null 2>&1
	if [ -s "/tmp/pin" ];then
		echo $(cat /tmp/pin)
	else
		echo $factoryPIN
	fi
	;;

	MODEL)
	rm -f /tmp/productinfo >/dev/null 2>&1
	nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1 
	echo $(grep 'product_name' /tmp/productinfo | cut -d : -f 2-)
	;;

	HOSTNAME_NO_BLANK)    # show hostname like ArcherA6v2
	rm -f /tmp/productinfo >/dev/null 2>&1
	nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1 
	hostname=$(grep 'product_name' /tmp/productinfo | cut -d : -f 2- | sed "s/ //g")
	version=$(grep 'product_ver' /tmp/productinfo | cut -d : -f 2-)
	version=${version%%.*}
	echo "${hostname}v${version}"
	;;

	HOSTNAME_BLANK)    # show hostname like Archer A6 v2
	rm -f /tmp/productinfo >/dev/null 2>&1
	nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1 
	hostname=$(grep 'product_name' /tmp/productinfo | cut -d : -f 2-)
	version=$(grep 'product_ver' /tmp/productinfo | cut -d : -f 2-)
	version=${version%%.*}
	echo "${hostname} v${version}"
	;;

	HOSTNAME_UNDERLINE)  #  show hostname like Archer_A6
	rm -f /tmp/productinfo >/dev/null 2>&1
	nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1 
	hostname=$(grep 'product_name' /tmp/productinfo | cut -d : -f 2- | sed "s/ /_/g")
	echo "${hostname}"
	;;

	
	FIRM)
	rm -f /tmp/productinfo >/dev/null 2>&1
	nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1 
	echo $(grep 'vendor_name' /tmp/productinfo | cut -d : -f 2-)
	;;
	
	WEBSITE)
	rm -f /tmp/productinfo >/dev/null 2>&1
	nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1 
	echo $(grep 'vendor_url' /tmp/productinfo | cut -d : -f 2-)
	;;
	
	HARDVERSION)
	rm -f /tmp/productinfo >/dev/null 2>&1
	nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1 
	echo $(grep 'product_ver' /tmp/productinfo | cut -d : -f 2-)
	;;

	LANGUAGE) 
	rm -f /tmp/productinfo >/dev/null 2>&1
	nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1 
	echo $(grep 'language' /tmp/productinfo | cut -d : -f 2-)
	;;
	
	PRODUCT_ID)
	rm -f /tmp/productinfo >/dev/null 2>&1
	nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1 
	echo $(grep 'product_id' /tmp/productinfo | cut -d : -f 2-)
	;;
	
	SPECIAL_ID)
	rm -f /tmp/productinfo >/dev/null 2>&1
	nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1 
	echo $(grep 'special_id' /tmp/productinfo | cut -d : -f 2-)
	;;

	DEV_ID)                                                      
	rm -f /tmp/deviceId >/dev/null 2>&1                           
	nvrammanager -r /tmp/deviceId -p device-id > /dev/null 2>&1
	echo $(grep 'dev_id' /tmp/deviceId | cut -d : -f 2-)
	;;

	HW_ID)                                                      
	rm -f /tmp/productinfo >/dev/null 2>&1                           
	nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1
	echo $(grep 'hw_id' /tmp/productinfo | cut -d : -f 2-)
	;;

	REGION)
	rm -f /tmp/productinfo >/dev/null 2>&1
	nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1 
	echo $(grep 'region' /tmp/productinfo | cut -d : -f 2-)
	;;

    
	SOFTVERSION)
	rm -f /tmp/softversion >/dev/null 2>&1
	nvrammanager -r /tmp/softversion -p soft-version >/dev/null 2>&1
	echo $(grep 'soft_ver' /tmp/softversion | cut -d : -f 2-)
	;;


	FW_ID)
	rm -f /tmp/softversion >/dev/null 2>&1
	nvrammanager -r /tmp/softversion -p soft-version >/dev/null 2>&1
	echo $(grep 'fw_id' /tmp/softversion | cut -d : -f 2-)
	;;
	
	OEM_ID)                                                      
	rm -f /tmp/productinfo >/dev/null 2>&1                           
	nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1
	echo $(grep 'oem_id' /tmp/productinfo | cut -d : -f 2-)
	;;
    
 	COUNTRY)                                                      
	rm -f /tmp/productinfo >/dev/null 2>&1                           
	nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1
	echo $(grep 'country' /tmp/productinfo | cut -d : -f 2-)
	;; 	
	*)
	usage
	;;
esac
