#!/bin/sh
# start switch
ssdk_sh debug phy set 0 0 0x1200 2>&1 1>-
ssdk_sh debug phy set 1 0 0x1200 2>&1 1>-
ssdk_sh debug phy set 2 0 0x1200 2>&1 1>-
ssdk_sh debug phy set 3 0 0x1200 2>&1 1>-
ssdk_sh debug phy set 4 0 0x1200 2>&1 1>-