#!/bin/sh
# Copyright (c) 2014 The Linux Foundation. All rights reserved.

. /lib/functions.sh

/etc/init.d/improxy enabled && [ "$ACTION" = "ifup" ] && [ "$INTERFACE" = "wan" -o "$INTERFACE" = "internet" -o "$INTERFACE" = "lan" ] && {
	/etc/init.d/improxy restart
}

/etc/init.d/improxy enabled && [ "$ACTION" = "ifdown" ] &&  {

    [ "$INTERFACE" = "wan" ] && {

		config_load network
		config_get iface "wan" ifname
        ipv4=`ip addr show $iface |grep "inet "`
        [ -z "$ipv4" ] && /etc/init.d/improxy restart
    }
}
