#!/bin/sh

. /lib/functions.sh

if [ "$INTERFACE" != "wan" -a "$INTERFACE" != "internet" -a "$INTERFACE" != "lan" -a "$INTERFACE" != "mobile" ]; then
    exit 0
fi

if [ "$ACTION" = "ifup" ]; then
    config_load usbshare
    config_get ftp global ftp
    config_get ftpex global ftpex
    config_get ftpex_port global ftpex_port

    if [ "$ftp" == "on" -a "$ftpex" == "on" ]; then
        local mode="all"
        ftpex add $ftpex_port $mode
    elif [ "$ftp" == "on" -a "$ftpex" == "off" ]; then
        local mode="ftp_only"
        ftpex add $ftpex_port $mode
    elif [ "$ftp" == "off" -a "$ftpex" == "on" ]; then      
        local mode="ftpex_only"
        ftpex add $ftpex_port $mode
    fi

elif [ "$ACTION" = "down" ]; then 
    config_load usbshare
    config_get ftpex_port global ftpex_port
    ftpex del $ftpex_port all
fi
