#!/bin/sh

[ -f /tmp/boot_done ] || exit 0
. /lib/functions.sh

if [ "$INTERFACE" != "lan" ]; then
    exit 0
fi

if [ "$ACTION" = "ifup" ]; then
    config_load usbshare
    config_get samba global samba

    if [ "$samba" == "on" ]; then
        /etc/init.d/samba restart
    fi
fi
