#!/bin/sh

# Copyright (C) 2009 OpenWrt.org

# echo ACTION=$ACTION, DEVPATH=$DEVPATH, SUBSYSTEM=$SUBSYSTEM, BUSNUM=$BUSNUM >/dev/console

# echo "--------------" >>/dev/console
#echo "busnum=$BUSNUM" >> /dev/console
#echo "action=$ACTION" >> /dev/console
#echo "intf=$INTERFACE" >> /dev/console
#echo "devnum=$DEVNUM" >> /dev/console
#echo "dev=$DEVICE" >> /dev/console
#echo "pdt=$PRODUCT" >> /dev/console
#echo "type=$TYPE" >> /dev/console
#echo "--------------" >>/dev/console

if [ "$DEVNUM" = "001" ]
then
    exit 0
fi

case "$BUSNUM" in
    001)
        USB="USB1"
        ;;
    002)
        USB="USB2"
        ;;
    *)
        exit 0
        ;;
esac

. /lib/usb/usb.sh

case "$ACTION" in
	add)
		# update LEDs
        ledcli ${USB}_ON

		usb_devconn $BUSNUM $DEVNUM $DEVPATH
		;;
	remove)
		# update LEDs
        ledcli ${USB}_OFF

		usb_devdisconn $DEVPATH
		;;
esac	
