#!/bin/sh

. /lib/functions.sh
local sysmode
config_load sysmode
config_get sysmode sysmode mode "router"
local country=`getfirm SPECIAL_ID`
if [ "$country" != "52550000" -o "$sysmode" = "ap" ]; then
	return 0
fi

/usr/lib/modem/handle_card.sh
