#!/bin/sh /etc/rc.common

SERVICE_DAEMONIZE=1

START=99

CONFIGFILE="/var/etc/cloud.cfg"
start()
{
	config_load cloud_svr

	echo "{" > $CONFIGFILE

	echo -e "\t\"cloud\":{" >> $CONFIGFILE
	config_get domain cloud domain
	echo -e "\t\t\"domain\":\""$domain"\"," >> $CONFIGFILE
	config_get port cloud port
	echo -e "\t\t\"port\":"$port >> $CONFIGFILE
	echo -e "\t}," >> $CONFIGFILE

	echo -e "\t\"default\":{" >> $CONFIGFILE
	config_get heart_beat default heartbeat_interval_ms
	echo -e "\t\t\"heartbeat_interval_ms\":"$heart_beat"," >> $CONFIGFILE
	config_get time_out default request_timeout_ms
	echo -e "\t\t\"request_timeout_ms\":"$time_out"," >> $CONFIGFILE
	config_get msg_num default "max_message_number"
	echo -e "\t\t\"max_message_number\":"$msg_num"," >> $CONFIGFILE
	config_get cli_num default max_client_number
	echo -e "\t\t\"max_client_number\":"$cli_num"," >> $CONFIGFILE
	config_get cer_f default cer_file
	echo -e "\t\t\"cer_file\":"\"$cer_f\" >> $CONFIGFILE
	echo -e "\t}," >> $CONFIGFILE

	echo -e "\t\"module\":{" >> $CONFIGFILE
	config_get kit module cloud_kit
	echo -e "\t\t\"cloud_kit\":\""$kit"\"" >> $CONFIGFILE
	echo -e "\t}" >> $CONFIGFILE

	echo "}" >> $CONFIGFILE

	service_start /usr/bin/cloud-brd -c $CONFIGFILE
}

stop()
{
	SERVICE_SIG=kill service_stop /usr/bin/cloud-brd
}
