#!/bin/sh /etc/rc.common

START=90
STOP=90

FFS_LIBDIR=/lib/ffs

ffs_intface() {
	. ${FFS_LIBDIR}/ffs_core.sh
	ffs_$*
}

start() {
	ffs_intface start
}

stop() {
	ffs_intface stop $1
}

restart() {
	ffs_intface restart
}

