#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2010 OpenWrt.org

START=45

FW_LIBDIR=/lib/firewall

fw() {
	. $FW_LIBDIR/core.sh
	fw_$1
}

start() {

#configure ip6tables.

[ "`uci get firewall.@defaults[0].disable_ipv6`" = 1 ] && {
uci set firewall.@defaults[0].disable_ipv6=0
[ "`uci get firewall.@zone[1].name`" = 'wan' ] && uci set firewall.@zone[1].network='wan internet wanv6 mobile'
uci commit
}
####################################

	fw start
}

stop() {
	fw stop
}

restart() {
	fw restart
}

reload() {
	fw reload
}
