#!/bin/sh /etc/rc.common

START=13
SERVICE_DAEMONIZE=1
start()
{
	service_start /usr/bin/ledctrl
}

stop()
{
#	[ -f /var/run/ledctrl ] && {
#		local pid=$(cat /var/run/ledctrl)
#		kill $pid
#		rm /var/run/ledctrl
#       rm /var/run/ledctrl_sock*
#  }
	service_stop /usr/bin/ledctrl
}

