#!/bin/sh /etc/rc.common
# Copyright(c) 2008-2014 Shenzhen TP-LINK Technologies Co.Ltd.
#
# Details : The init script for logd.
# Author  : Ye Qianchuan <yeqianchuan@tp-link.net>
# Version : 1.0
# Date    : 17 Jul, 2014

SERVICE_DAEMONIZE=1

boot() {
    return 0
}

get_log_size() {
    config_get log_size $1 log_size 128
}

start() {
    config_load system
    local args log_size
    config_foreach get_log_size system
    args="-C ${log_size}"
    service_start /usr/sbin/logd $args
}

stop() {
    service_stop /usr/sbin/logd
}
