#!/bin/sh /etc/rc.common
# Copyright (C) 2015 zengwei <zengwei@tp-link.net>

START=99

start_monitor() {
	local offline_dl_enable=$(uci get offline_download.global.enable)
	if [ "$offline_dl_enable" == "on" ]; then 
		ps -w |grep -v grep |grep "lua /lib/offline_download/offline_download_op.lua startmonitor"
		[ $? -eq 0 ] || lua /lib/offline_download/offline_download_op.lua startmonitor &
	else
		stop_apps
		stop_monitor
	fi
}

stop_monitor() {
	ps -w |grep "lua /lib/offline_download/offline_download_op.lua startmonitor" |grep -v grep |awk '{print $1}'|xargs kill -9
}

restart_monitor() {
	stop_monitor
	start_monitor
}

stop_apps() {
	lua /lib/offline_download/offline_download_op.lua stopapps
}

update_schedule() {
	#lua /lib/offline_download/offline_download_op.lua updatesche
	local schedule_enable=$(uci get offline_download.advanced.schedule_enable)
	if [ "$schedule_enable" == "on" ]; then
		local schedule=$(uci get offline_download.advanced.schedule)
		tsched_conf -a offline_download offline_download_schedule "$schedule"
		tsched_conf -u offline_download
	fi
}

start() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	if [ "$sysmode" = "router" ]; then
		#set the system cache var
		#sysctl -w vm.vfs_cache_pressure=200
		#sysctl -w vm.min_free_kbytes=10190
		
		#set the cron for checking monitor process
		echo "*/10 * * * * . /etc/init.d/offline_download && start_monitor" >> /etc/crontabs/root
		/etc/init.d/cron restart
		
		update_schedule
		
		#start monitor process
		start_monitor
	fi
}

stop() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	if [ "$sysmode" = "router" ]; then
		stop_monitor
		stop_apps
	fi
}
