#!/bin/sh /etc/rc.common

START=99

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {
	echo "phyport start ......."
        . /lib/switch/core.sh
	setup_duplex
	setup_ports
	sleep 2
}

restart() {
	stop
        start
}

shutdown() {
	echo "Shutdown switch!"
}

stop() {
	. /lib/switch/core.sh
	unsetup_duplex
}

reload() {
        start
}
