#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2010 OpenWrt.org

START=47

check_hnat_status() {

		#for old pc and qos,hnat does't depend on these status. this is only for temporary.
		[ -f /etc/config/parental_control_v2 ] || {
			# echo "pc/qos v1:hnat_enable is always set to 1" >/dev/console
			echo "#######WARNING####### Parent Control V2 Support ONLY!" >/dev/console
			return 1
		}
		
		qos_en=$(uci get qos_v2.settings.enable)
		tfs_en=$(uci get tfstats.switch.enable)
		[ -z "$qos_en" ] && qos_en="off"
		[ -z "$tfs_en" ] && tfs_en="off"

		pc_v2_en="off"
		pc_v2_search=$(grep "name" /etc/config/parental_control_v2)
		[ -n "$pc_v2_search" ] && pc_v2_en="on"
				
		if [ "$qos_en" == "off" -a "$tfs_en" == "off" -a "$pc_v2_en" == "off" ]
		then
			echo "check_hnat_status:1" >/dev/console
			return 1
		else
			echo "check_hnat_status:0" >/dev/console
		  return 0
		fi 
}

boot() {

    #for old fw->new fw,the hw_enable has changed to boost_enable;
    echo "uci try old hw_enable:" >/dev/console
    tmp="$(uci get nat.nat_global.hw_enable)" 
  
    [ -n "$tmp" ] && {
    	echo "Still has hw_enable:$tmp!!!" >/dev/console
    	
      #copy value to new variable:boost_enable
    	uci set nat.nat_global.boost_enable=$tmp
    	
    	#add new variable:hnat_enable
    	check_hnat_status
    	if [ $? == 1 ]
    	then
    		uci set nat.nat_global.hnat_enable="on"
    	else
    	  uci set nat.nat_global.hnat_enable="off"
    	fi
    	
    	#remove old variable:hw_enable
    	uci delete nat.nat_global.hw_enable
   		uci commit
    }
    
    # when iptv is enabled, qca-hnat will starting in iptv init script.
    [ "$(uci get iptv.iptv.enable)" == "on" ] || qca-hnat start;
}

start() {
    qca-hnat start
}

stop() {
    qca-hnat stop
}

restart() {
   qca-hnat stop
   qca-hnat start
}
