#!/bin/sh /etc/rc.common

START=99

start()
{
	local kernel_version=$(uname -r)
	insmod /lib/modules/$kernel_version/sdt_afc.ko
	pgrep sdt_afc_control || /usr/sbin/sdt_afc_control &
}

stop()
{
	rmmod sdt_afc
	pgrep sdt_afc_control |xargs kill -9
	
}
