#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=68

have_nss() {
	[ -n "$(cat /proc/cpuinfo | grep DB149)" ] && echo 1 && return
	[ -n "$(cat /proc/cpuinfo | grep AP145)" ] && echo 1 && return
	[ -n "$(cat /proc/cpuinfo | grep AP148)" ] && echo 1 && return

	echo 0
}

load_sfe() {
	local kernel_version=$(uname -r)

	[ -e "/lib/modules/$kernel_version/shortcut-fe-cm.ko" ] && {
		[ -d /sys/module/shortcut_fe_cm ] || insmod /lib/modules/$kernel_version/shortcut-fe-cm.ko
	}
	[ -e "/lib/modules/$kernel_version/fast-classifier.ko" ] && {
		[ -d /sys/module/fast_classifier ] || insmod /lib/modules/$kernel_version/fast-classifier.ko
	}
}

boot() {
	# when iptv is enabled, shortcut-fe will starting in iptv init script.
	[ "$(uci get iptv.iptv.enable)" == "on" ] || start;
}

start() {
	local nat_enable=$(uci get nat.@nat_global[0].enable)
	local nat_boost_enable=$(uci get nat.@nat_global[0].boost_enable)
	[ "$nat_enable" == "off" -o "$nat_boost_enable" == "off" ] && {
		stop
		return
	}

	[ "$(have_nss)" = "1" ] || load_sfe
	echo "SFE STARTED---" >/dev/console
	echo 1 >/tmp/sfe_status
}

stop() {
	[ -d /sys/module/shortcut_fe_cm ] && rmmod shortcut_fe_cm
	[ -d /sys/module/fast_classifier ] && rmmod fast_classifier
	echo 0 >/tmp/sfe_status
	echo "SFE STOPPED---" >/dev/console
}
