#!/bin/sh /etc/rc.common

START=19
STOP=91

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {
        

        setup_switch() { return 0; }
        . /lib/switch/switch.sh
        setup_switch

		local sysmode
		config_load sysmode
		config_get sysmode sysmode mode "router"
			
		. /lib/switch/core.sh

		if [ "$sysmode" = "router" ]; then
        	setup_vlan # switch_bind_mac
		fi

		unsetup_ports # switch_link_down
}

restart() {
        stop
        start
        env -i ACTION=RESTART /sbin/hotplug-call switch
}

shutdown() {
        echo "do nothing"
}

stop() {
        echo "do nothing"
}

reload() {
        start
}
