#!/bin/sh /etc/rc.common

START=51

SERVICE_DAEMONIZE=1
start()
{
	local sysmode
	config_load sysmode
	config_load onemesh
	config_get sysmode sysmode mode "router"
	config_get onemesh_enable onemesh enable "on"
	if [ "$sysmode" = "router" -a "$onemesh_enable" = "on" ]; then
		service_start "/bin/nice" -n -5 /usr/bin/sync-server
	fi
}

stop()
{
	service_stop /usr/bin/sync-server
}
