#!/bin/sh /etc/rc.common

START=13
SERVICE_DAEMONIZE=1
cycle()
{
	sleep 2 
	if [ "$(/sbin/is_cal)" = "true" ]; then
		ledcli STATUS_BLINK
	else
		ledcli STATUS_CALIBRATE
	fi
}
start()
{
	cycle &
      
}
