#!/bin/sh /etc/rc.common

START=50

SERVICE_DAEMONIZE=1
start()
{
	if [ "$(uci get factory.factorymode.enable)" = "yes" ];	then
		service_start /usr/bin/tddp
	fi
}

stop()
{
	service_stop /usr/bin/tddp
}
