#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2010 OpenWrt.org

START=12

TS_LIBDIR=/lib/time_settings

TIME_SETTINGS_MOD_ID=279
LOG_INF_SERVICE_START=504
LOG_INF_SERVICE_STOP=505
LOG_INF_SERVICE_RESTART=508

start() {
	$TS_LIBDIR/set_time
	#ori_time=$(uci get profile.@global[0].factory_time -c /etc/profile.d)
	#date -s "$ori_time"
	
	#use softversion compile time as the initial time.
	local version=`getfirm SOFTVERSION|awk '{print $3}'`
 	local curTime=${version:0-3:4}'-'${version:4-5:2}'-'${version:6-7:2}
 	date -s $curTime" 00:00:00"

	# the first date -k before date -s does not take effect, (1) call date -k again, or (2) change the sequence of them can solve this issue.
	# here use the first one, date -k again
	date -k

	logx -p $$ $TIME_SETTINGS_MOD_ID $LOG_INF_SERVICE_START
}

stop() {
	echo "do nothing"
	logx -p $$ $TIME_SETTINGS_MOD_ID $LOG_INF_SERVICE_STOP
}

restart() {
	$TS_LIBDIR/set_time
	logx -p $$ $TIME_SETTINGS_MOD_ID $LOG_INF_SERVICE_RESTART
}

reload() {
	$TS_LIBDIR/set_time
	[ -f /etc/init.d/cron ] && /etc/init.d/cron stop
	[ -f /etc/init.d/cron ] && /etc/init.d/cron start
	logx -p $$ $TIME_SETTINGS_MOD_ID $LOG_INF_SERVICE_RESTART
}
