#!/bin/sh /etc/rc.common

START=50

#SERVICE_DAEMONIZE=1
start()
{
	"/bin/nice" -n -5 /usr/bin/tmpServer &>/dev/null &
	"/bin/nice" -n -5 /usr/bin/tdpServer &>/dev/null &
	"/bin/nice" -n -5 /usr/bin/pfclient &>/dev/null &
}

stop()
{
	local pfclient_pid=`ps|grep /usr/bin/pfclient|grep -v 'grep'|awk '{print $1}'`
	local tdpServer_pid=`ps|grep /usr/bin/tdpServer|grep -v 'grep'|awk '{print $1}'`
	local tmpServer_pid=`ps|grep /usr/bin/tmpServer|grep -v 'grep'|awk '{print $1}'`
    if [ -n "$pfclient_pid" ];then
        for pid in $pfclient_pid; do
            kill -9 "$pid"
        done
    fi
    if [ -n "$tdpServer_pid" ];then
        for pid in $tdpServer_pid; do
            kill -9 "$pid"
        done
    fi
    if [ -n "$tmpServer_pid" ];then
        for pid in $tmpServer_pid; do
            kill -9 "$pid"
        done
    fi
}

