#!/bin/sh /etc/rc.common

START=80

debug() {
    echo $1 >/dev/console 2>&1
}

start() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	local country=`getfirm SPECIAL_ID`
	if [ "$country" != "52550000" -o "$sysmode" = "ap" ]; then
		return 0
	fi	
	uci set modem.modemisp.pinlock=0
	uci set modem.modemconf.modemstatus=0
	uci commit modem
	/usr/lib/modem/handle_card_process.sh &
    return 0
}

stop() {
    return 0
}

reload() {
    return 0	
}
