#!/bin/sh /etc/rc.common

START=50
STOP=90
mtd_name=`cat /proc/mtd | grep "ART" | grep -o "mtd."`
SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {
	echo 3 > /proc/sys/vm/drop_caches
	[ -c /dev/dk0 ] || mknod /dev/dk0 c 63 0
	[ -c /dev/dk1 ] || mknod /dev/dk1 c 63 1
	[ -L /dev/caldata ] || ln -s /dev/${mtd_name} /dev/caldata
    
	if [ "$(/sbin/is_cal)" = "true" ]; then
		/sbin/wifi default &> /dev/null
		/sbin/wifi_firm
		/sbin/wifi_check_country
		/sbin/wifi
	else
		# the art procedure has been moved advance for 32M DDR product.
		# because art needs more memory than it own when finish initialization.
		#switch_link_up
		#cd /usr/sbin/
		#/etc/init.d/art start
		#cd /
		echo "wireless do nothing"
	fi
	return 0
}

restart() {
	/sbin/wifi
	return 0
}

shutdown() {
	killall -9 hostapd
	# do not call wifi down!
	#/sbin/wifi down
	return 0
}

stop() {
	/sbin/wifi down
	return 0
}

reload() {
	/sbin/wifi reload
	return 0
}
