#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2010 OpenWrt.org

START=99

TS_LIBDIR=/lib/time_settings

start() {
	$TS_LIBDIR/boot_done
}

stop() {
	echo "do nothing"
}

restart() {
	$TS_LIBDIR/boot_done
}

reload() {
	$TS_LIBDIR/boot_done
}
