#!/bin/sh /etc/rc.common   

START=13


syslog()
{
	logx -p $$ 293 200 "$1"
}


mac_check()
{
	local mac=$(getfirm MAC)
	echo $mac | grep -qE '^[a-fA-F0-9]{2}\-[a-fA-F0-9]{2}\-[a-fA-F0-9]{2}\-[a-fA-F0-9]{2}\-[a-fA-F0-9]{2}\-[a-fA-F0-9]{2}$' > /dev/null 2>&1
	local ret=$?
	if [ $ret = 0 ];then
		echo $mac | grep -qE '^(0{1,2}-){5}0{1,2}$' > /dev/null 2>&1
		ret=$?
		if [ $ret = 0 ];then 
			echo "MAC:00-0A-EB-AC-25-00" > /tmp/default-mac  > /dev/null 2>&1
			nvrammanager -w /tmp/default-mac -p default-mac  > /dev/null 2>&1		
			echo 1
			return
		else
			echo $mac | grep -qE '^[0-9A-Fa-f]{1}[13579bdfBDF]{1}(\-[A-Fa-f0-9]{2}){5}$' > /dev/null 2>&1
			ret=$?
			if [ $ret = 0 ];then 		
				echo 1
				echo "MAC:00-0A-EB-AC-25-00" > /tmp/default-mac  > /dev/null 2>&1
				nvrammanager -w /tmp/default-mac -p default-mac  > /dev/null 2>&1
				return
			fi	
			echo 0	
		fi			
	else
		echo 1
		echo "MAC:00-0A-EB-AC-25-00" > /tmp/default-mac  > /dev/null 2>&1
		nvrammanager -w /tmp/default-mac -p default-mac  > /dev/null 2>&1
	fi	
}

pin_check()
{
	local pin=$(getfirm PIN)
#	if [ ${#pin} -eq 8 ];then
#		echo 1
#		return
#	fi
	echo $pin | grep -qE '^[0-9]{8}$' > /dev/null 2>&1
	local ret=$?
	if [ $ret = 1 ];then
		echo 1
		return
	fi

	numSel()
	{
		eval echo ${pin:$1:1}
	}

	local count=0
	local n=0
	for i in `seq 8` ; do
		if [ $((i%2)) -eq 1 ];then
			n=1
		else
			n=3
		fi
		local sel=$((8-i))
		local sum=`numSel $sel` 
		count=$((n*sum+count))
	done

	if [ $((count%10)) -eq 0 ];then
		echo 0
	else
		echo 1
	fi
	return
}

productInfo_check()
{
	local productid=$(getfirm PRODUCT_ID)
	if [ "$productid" != "00070005" ];then
		echo 1
		return 
	fi
	local product_name=
	rm -rf /tmp/productinfo > /dev/null 2>&1
	nvrammanager -r /tmp/productinfo -p product-info > /dev/null 2>&1
	product_name=$(grep 'product_name' /tmp/productinfo | cut -d : -f 2-)
	if [ "$product_name" != "Archer C7" ];then
		echo 1
	else
		echo 0
	fi
	return
}
radio_check()
{
	/usr/bin/radio_verify -c > /dev/null 2>&1
	local ret=$?
	if [ $ret = 0 ];then
		echo 0
	elif [ $ret = 2 ];then
		echo 2
	else
		echo 1
	fi
}
deviceId_check()
{
	local devid=$(getfirm DEV_ID)
	if [ ${#devid} -gt 64 -o ${#devid} -eq 0 ];then
		echo 1
		return
	fi

	echo $devid | grep -qE '[^0-9a-zA-Z]' > /dev/null 2>&1
	local ret=$?
	if [ $ret = 0 ];then
		echo 1
	else
		echo 0
	fi
}

boot() {

	local	result1=$(mac_check)
	local	result2=$(pin_check)
	local	result3=$(productInfo_check)
	local	result4=$(radio_check)
	local	result5=$(deviceId_check)
	
	errorNum="$result1$result2$result3$result4$result5"

	if [ "$errorNum" != "00000" ];then 
		syslog $errorNum
	fi

}

start() {
    return 0
}

stop() {
    return 0
}
