#!/bin/sh /etc/rc.common   

START=99zz
STOP=90


boot() {
    v=$(/usr/sbin/devmem 0x18040008 32)
    echo $v
    v=$(($v |0x80000))
    echo $v
    /usr/sbin/devmem 0x18040008 32 $v

    mv /lib/modules/ehci-hcd.ko /lib/modules/$(uname -r)/
    insmod /lib/modules/$(uname -r)/ehci-hcd.ko
}

start() {
    return 0
}

stop() {
    return 0
}
